### ISSUE TITLE
build succeed, server failing

### ISSUE THREAD

**Issue by vorcigernix** [thgh/now-sapper#10]
Hi, 
I tried to implement it in my project but getting weird error from Now runtime:
```
2019-10-13T07:53:29.934Z	undefined	ERROR	Server is not listening { Error: Cannot find module '__sapper__/build/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/task/launcher.js:17:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }
Duration: 133.81 ms  Billed Duration: 200 ms  Memory Size: 3008 MB  Max Memory Used: 27 MB	
RequestId: dc82cba4-54a8-4301-8c66-cf016c239fcd Error: Runtime exited with error: exit status 1
Runtime.ExitError
```
I suspect that the legacy build is required, but I can't do that with webpack. Is there any workaround? Should I try to move the solution to rollup?

**Comment by vorcigernix** [comment]
I fixed issue by cloning the example template and copying my files over. I still suspect that webpack is the culprit, but I am okay with whole thing working.
