### ISSUE TITLE
modules not installed

### ISSUE THREAD

**Issue by 0xd61** [thgh/now-sapper#5]
I'm trying to use this builder to deploy my sapper application with now. After deployment the site works. Although I'm getting the following error:
```
{ Error: Cannot find module 'node-fetch'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at send (/var/task/user/__sapper__/build/server/account-920fc8e5.js:8:50)
    at Object.post (/var/task/user/__sapper__/build/server/account-920fc8e5.js:51:10)
    at getApiKey (/var/task/user/__sapper__/build/server/server.js:35638:18)
    at get (/var/task/user/__sapper__/build/server/server.js:35613:27)
    at handle_route (/var/task/user/__sapper__/build/server/server.js:35803:11)
    at Array.find_route (/var/task/user/__sapper__/build/server/server.js:35817:5) code: 'MODULE_NOT_FOUND' }
```

I'm using `node-fetch` as dependency in my `package.json`.

**Comment by thgh** [comment]
Do you use import or require?

**Comment by 0xd61** [comment]
I use require:

```
  const fetch = process.browser ? window.fetch : require("node-fetch").default;
```

**Comment by thgh** [comment]
This project does not use node_modules, it expects all dependencies to be rolled up. You could try something along these lines:

```
import _fetch from 'node-fetch'
if (!process.browser) {
  window.fetch = _fetch
}

```

**Comment by 0xd61** [comment]
Awesome, thanks!
